export const SPECIFICATIONS = [
    "Dimentions",
    "Weight",
    "Material",
    "Color",
    "Finish",
    "Capacity",
    "Power Requirements",
    "Endurance",
    "Durability",
    "Corrosion",
    "Temperature Range",
    "Pressure Rating",
    "Vibration Resistance",
    "Shock Resistance",
    "Water Resistance",
    "Fire Resistance",
    "UV Resistance",
    "Chemical Resistance",
    "Biocompatibility",
    "Ergonomics",
    "Usability",
    "Comfort",
    "Aesthetics",
    "Brand Identity",
    "Certifications",
    "Standards Compliance",
    "Regulatory Requirements",
    "Safety Features",
    "Environmental Impact",
    "Sustainability",
    "Recyclability",
    "Warranty",
    "Maintenance",
    "Repairability",
    "Upgradability",
    "Compatibility",
    "Interoperability",
    "Integration",
    "Connectivity",
    "User Interface",
    "User Experience",
    "Performance",
    "Reliability",
    "Scalability",
    "Security",
    "Privacy",
    "Data Protection",
    "Compliance",
    "Legal Requirements",
    "Ethical Considerations",
    "Social Responsibility",
    "Economic Impact",
    "Cost",
    "Value",
    "ROI",
    "Market Potential",
    "Competitive Advantage",
    "Differentiation",
    "Innovation",
    "Future Potential",
    "Longevity",
    "Replacement",
    "Disposal",
    "End of Life",
    "Circular Economy",
    "Supply Chain Transparency",
    "Traceability",
    "Accountability",
    "Transparency",
    "Openness",
    "Collaboration",
    "Partnerships",
    "Innovation Ecosystem",
    "Research and Development",
    "Intellectual Property",
    "Patents",
    "Trademarks",
    "Copyrights",
    "Licensing",
    "Royalties",
    "Revenue Streams",
    "Growth Potential",
]